2024-02-24 22:37:37,145 WDM   INFO     ====== WebDriver manager ======
2024-02-24 22:37:37,242 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-24 22:37:37,827 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-24 22:37:38,087 WDM   INFO     Driver [/home/dhruv/.wdm/drivers/chromedriver/linux64/120.0.6099.109/chromedriver-linux64/chromedriver] found in cache
2024-02-24 22:38:56,318 WDM   INFO     ====== WebDriver manager ======
2024-02-24 22:38:56,414 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-24 22:38:56,712 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-24 22:38:57,144 WDM   INFO     Driver [/home/dhruv/.wdm/drivers/chromedriver/linux64/120.0.6099.109/chromedriver-linux64/chromedriver] found in cache
2024-02-29 13:34:59,512 WDM   INFO     ====== WebDriver manager ======
2024-02-29 13:34:59,620 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 13:34:59,977 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 13:35:00,175 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 13:35:00,634 WDM   INFO     WebDriver version 120.0.6099.109 selected
2024-02-29 13:35:00,636 WDM   INFO     Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/120.0.6099.109/linux64/chromedriver-linux64.zip
2024-02-29 13:35:00,636 WDM   INFO     About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/120.0.6099.109/linux64/chromedriver-linux64.zip
2024-02-29 13:35:00,885 WDM   INFO     Driver downloading response is 200
2024-02-29 13:35:01,743 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 13:35:02,127 WDM   INFO     Driver has been saved in cache [/home/dhruv/.wdm/drivers/chromedriver/linux64/120.0.6099.109]
2024-02-29 13:36:20,788 WDM   INFO     ====== WebDriver manager ======
2024-02-29 13:36:20,882 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 13:36:21,178 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 13:36:21,361 WDM   INFO     Driver [/home/dhruv/.wdm/drivers/chromedriver/linux64/120.0.6099.109/chromedriver-linux64/chromedriver] found in cache
2024-02-29 14:13:03,547 WDM   INFO     ====== WebDriver manager ======
2024-02-29 14:13:04,081 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 14:13:04,435 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 14:13:05,136 WDM   INFO     Driver [/home/dhruv/.wdm/drivers/chromedriver/linux64/120.0.6099.109/chromedriver-linux64/chromedriver] found in cache
2024-02-29 14:14:24,289 WDM   INFO     ====== WebDriver manager ======
2024-02-29 14:14:24,885 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 14:14:25,252 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 14:14:25,560 WDM   INFO     Driver [/home/dhruv/.wdm/drivers/chromedriver/linux64/120.0.6099.109/chromedriver-linux64/chromedriver] found in cache
2024-02-29 15:36:12,550 WDM   INFO     ====== WebDriver manager ======
2024-02-29 15:36:12,637 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 15:36:12,864 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 15:36:13,049 WDM   INFO     Driver [/home/dhruv/.wdm/drivers/chromedriver/linux64/120.0.6099.109/chromedriver-linux64/chromedriver] found in cache
2024-02-29 15:36:43,829 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4b130>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,830 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a470>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,834 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49c00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,836 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49930>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,838 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4ba30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,838 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4aef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,842 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bd00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,843 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bc10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,844 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bfa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,846 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4250>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,849 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e44c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,850 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4670>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,852 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e48e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,853 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,855 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4d00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,857 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4be20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,857 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4ba90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,858 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bbe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,859 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4970>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,859 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4040>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,860 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,861 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5210>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,861 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5480>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,862 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5630>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,862 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e58a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,863 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5b10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,863 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5cc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,864 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bac0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,865 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a230>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,865 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4baf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,866 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5930>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,867 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5150>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,867 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e50f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,868 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4880>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,868 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5f30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,869 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e60e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,871 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6350>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,872 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e65c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,872 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6770>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,875 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4ba30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,875 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49cc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,876 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4be20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,877 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bf10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,877 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49f00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,877 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49bd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,878 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4b1f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,879 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49cf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,879 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,880 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4040>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,880 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4f70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,881 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4160>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,882 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5360>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,882 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,882 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e55a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,884 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4ba00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,884 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49630>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,884 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bee0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,885 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49ba0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,886 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bf10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,887 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a7d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,888 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4ba90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,888 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4ba30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,889 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e53c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,890 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5c00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,890 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5c30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,891 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4400>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,892 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4490>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,892 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,893 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a440>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,894 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49960>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,894 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4be20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,894 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bcd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,895 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,896 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49bd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,896 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a770>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,897 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e43d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,897 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e63b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,898 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5810>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,899 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4bb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,899 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6b30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,899 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6ce0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,900 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,901 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bf70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,901 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a200>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,903 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49c90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,904 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4be50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,904 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a7a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,905 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a230>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,906 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bb20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,906 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6ef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,907 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,907 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5120>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,908 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4670>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,909 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e7370>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,909 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e75e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,910 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e7790>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,911 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b495d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,911 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a710>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,911 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4be20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,912 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49f00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,913 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49e40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,913 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bee0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,914 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e73d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,914 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4f10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,915 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6fb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,915 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e7a00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,916 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e7c70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,916 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e7e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,917 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442440d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,918 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5b10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,918 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e7970>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,919 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e7910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,920 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49c90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,920 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a6e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,921 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49de0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,922 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4be80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,922 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a7d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,923 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a080>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,923 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44244130>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,924 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44244400>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,925 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44244670>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,925 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442448e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,926 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44244a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,927 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4be20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,927 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a7d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,928 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4beb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,929 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4ba00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,929 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49930>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,930 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bb20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,930 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6fe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,931 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e5b10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,931 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44244d30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,932 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44244fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,933 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44245210>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,933 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442453c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,934 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44245630>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,935 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6fb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,935 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6ef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,936 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49cc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,936 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4b160>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,937 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a5f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,938 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4baf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,938 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4be80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,938 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442455d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,939 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44244e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,940 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44244cd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,940 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44245960>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,941 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44245bd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,941 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44245e40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,942 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44245ff0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,943 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4b940>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,943 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a770>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,944 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bb50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,945 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bb20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,945 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e4c40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,946 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e73d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,947 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44245c30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,947 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442446d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,947 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44245000>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,948 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246260>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,949 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442464d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,949 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246680>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,950 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442468f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,951 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e7880>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,951 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6fe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,952 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a7a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,952 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a7d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,953 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49f00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,954 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bc10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,954 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4b9a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,954 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246aa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,955 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44245000>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,956 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44244ee0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,956 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246c50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,957 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246ec0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,957 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247130>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,958 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442472e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,959 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4bcd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,959 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49c90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,959 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4b910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,960 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a7a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,961 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e49a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,961 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6fe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,962 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,962 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442456f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,963 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247580>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,964 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442477f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,964 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247a60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,964 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,966 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247e80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,966 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e48e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,967 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff441e6f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,968 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442455d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,968 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442475e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,968 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247550>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,969 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4be80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,970 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b4a6e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,970 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49990>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,971 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44b49c90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,971 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442a4040>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,972 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442a41f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,973 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442a4460>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,973 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442a46d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,976 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442a4880>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,978 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246f20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,979 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442461d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,980 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247760>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,981 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442479a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,982 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247cd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,982 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,984 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442446d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,985 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246cb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,985 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246bc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,987 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442470a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,988 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247130>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,988 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247190>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,990 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442466e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,990 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,991 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442468c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,993 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246ce0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,994 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246e00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,994 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246b90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,996 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44246f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,996 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442457b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,997 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442479d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,998 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247730>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:43,999 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44247e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:44,000 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442457e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:44,001 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff442468f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:44,002 urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44244c40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:44,003 urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44245870>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:36:44,004 urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff44244eb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f2df347033bcfce7dbe899ddca4e16f7/element
2024-02-29 15:37:05,838 WDM   INFO     ====== WebDriver manager ======
2024-02-29 15:37:05,928 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 15:37:06,184 WDM   INFO     Get LATEST chromedriver version for google-chrome
2024-02-29 15:37:06,417 WDM   INFO     Driver [/home/dhruv/.wdm/drivers/chromedriver/linux64/120.0.6099.109/chromedriver-linux64/chromedriver] found in cache
